package snax;

import java.io.File;
import java.io.IOException;

public class AppRegister {
    private final String mainPath = System.getProperty("user.dir");

    private final String tomlName = "snaxAppRegistrations.toml";

    public String configPath;

    public RegistrationParser appMaster;

    public AppRegister() {
        System.out.println(
                "===============================Running startup service for SnaxAppRegistration===============================");
        this.configPath = buildConfigPath(isUnix(this.mainPath));

        System.out.println("CONFIG FILE AT: " + this.configPath);

        this.appMaster = new RegistrationParser(new File(this.configPath));

    }

    /**
     * Given a file path, isUnix will return a boolean determining if the file path given is a Unix based file format
     * The function also checks the System property of os.name for absolute sanity regarding the check
     * @return boolean -> Is a Unix system or not
     */
    public boolean isUnix(String filePath) {
        // sanity check for windows machine -> check os detection from java os
        if (System.getProperty("os.name").startsWith("Windows")) {
            return false;
        }

        for (int i = 0; i < filePath.length(); i++) {
            //need to be careful in this check, irregular length file paths/names can cause program freeze or crash
            if (filePath.charAt(i) == '\\') {
                return false;
            }

        }

        return true;
    }

    public String buildConfigPath(boolean unix) {
        String separator = unix ? "/" : "\\";
        String systemType = unix ? "Unix/BSD" : "Windows";

        System.out.println("Detected system as " + systemType + " machine");

        String dirPath = checkDir(new File(this.mainPath + separator + "config" + separator));

        File filePath = new File(dirPath + separator + tomlName);

        createFile(filePath);

        return filePath.toString();

    }

    public String checkDir(File directory) {

        if (!directory.exists()) {
            directory.mkdirs();
        }

        return directory.toString();

    }

    public void createFile(File file) {
        System.out.println("Searching for snaxAppRegistration config file");

        try {
        
            //TODO: add a autogenerated file, not just creating it add content
            if (!file.exists()) {
                boolean created = file.createNewFile();

                if (created) {
                    System.out.println("Successfully initialized config file");
                }

                else if (!created) {
                    System.out.println("Failed to initialize or find the config file");
                }

            }

            else {
                System.out.println("Loading preexisting config file");
            }

        }

        catch (IOException e) {
            System.out.println("An error occurred when trying to create the config file" + e);
            e.printStackTrace();
        }

    }

}
